{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stable-app.fullname" . }}
data:
{{- with .Values.configMap.data }}
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}