{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stable-app.fullname" . }}
type: Opaque
data:
{{- with .Values.secret.data }}
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}