{{- if eq .Values.deploy.strategy.type "canary" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "skb-app-gradle.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "skb-app-gradle.selectorLabels" . | nindent 4 }}
{{- else if eq .Values.deploy.strategy.type "blueGreen" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-active-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "skb-app-gradle.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "skb-app-gradle.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-preview-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "skb-app-gradle.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "skb-app-gradle.selectorLabels" . | nindent 4 }}
{{- end}}
