apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-active-service
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    {{- include "stable-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "stable-app.selectorLabels" . | nindent 4 }}
---
{{- if eq .Values.deploy.strategy.type "blueGreen" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-preview-service
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    {{- include "stable-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "stable-app.selectorLabels" . | nindent 4 }}
{{- end}}